name: 'Write It Down Action'
description: 'A no-op GitHub Action'
author: 'Write It Down'
inputs:
  from:
    description: 'Starting commit reference (e.g., HEAD^)'
    required: false
    default: ''
  to:
    description: 'Ending commit reference (e.g., HEAD)'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Setup CLI
      run: |
        mkdir -p ~/.write-it-down/bin
        curl -fsSL https://write-it-down-826b0.web.app/cli/write-it-down -o ~/.write-it-down/bin/write-it-down
        chmod +x ~/.write-it-down/bin/write-it-down
      shell: bash
    - name: Run write-it-down ci
      run: |
        CMD="~/.write-it-down/bin/write-it-down ci"
        if [ -n "${{ inputs.from }}" ]; then
          CMD="$CMD --from ${{ inputs.from }}"
        fi
        if [ -n "${{ inputs.to }}" ]; then
          CMD="$CMD --to ${{ inputs.to }}"
        fi
        eval $CMD
      shell: bash
